In [6]:
import json
import pandas as pd 
from tqdm import tqdm

In [8]:
def read_data(fpath, is_test=False):
  if is_test:
    data = {'id': [], 'text': [], 'image': []}
    js_obj = json.load(open(fpath, encoding='utf-8'))
    for obj in tqdm(js_obj):
      data['id'].append(obj['id'])
      data['image'].append(obj['img_path'])
      data['text'].append(obj['text'])
  else:
    data = {'id': [], 'text': [], 'image': [], 'label': []}
    js_obj = json.load(open(fpath, encoding='utf-8'))
    for obj in tqdm(js_obj):
      data['id'].append(obj['id'])
      data['image'].append(obj['img_path'])
      data['text'].append(obj['text'])
      data['label'].append(obj['class_label'])
  return pd.DataFrame.from_dict(data)

labels = read_data("../data/arabic_memes_propaganda_araieval_24_dev.json")
preds = pd.read_csv("task2C_kevinmathew 2.tsv", sep='\t')

100%|██████████| 312/312 [00:00<00:00, 889010.09it/s]


In [9]:
labels

id  \
0    data/arabic_memes_fb_insta_pinterest/Instagram...   
1    data/arabic_memes_fb_insta_pinterest/Pinterest...   
2    data/arabic_memes_fb_insta_pinterest/Instagram...   
3    data/arabic_memes_fb_insta_pinterest/Pinterest...   
4    data/arabic_memes_fb_insta_pinterest/Instagram...   
..                                                 ...   
307  data/fb_memes/ArabianMemez/272646015_128128777...   
308  data/arabic_memes_fb_insta_pinterest/Instagram...   
309  data/arabic_memes_fb_insta_pinterest/Pinterest...   
310  data/arabic_memes_fb_insta_pinterest/Instagram...   
311  data/arabic_memes_fb_insta_pinterest/Pinterest...   

                                                  text  \
0    - انا من حقي اقول اني مبحبش الشتا \n= وانا من ...   
1    أنا مش هضعف تاني قصادك أنا مش هرجع ابص ورايا.....   
2    -لما الكراش يتجاهلني\n=..\nMe\nده باين عليه بي...   
3    الطفل لما يخلوه مع\nمع الأب\nمع الأم\nمع الأخت...   
4    هي بقي نونوت معايا اقولك كل واحد فينا يروح لحا...   
..                                                 ...   
307  نضال الفيمنست وهي فاتحة نت \nفاتحة نت من اخترا...   
308  أبو أحمد اتبهدل معانا أوي يجما عه\nتب9نحمد\nأن...   
309  ابوك وامك بعد ما ربوك على ان مفيش راجل بيعيط و...   
310  لما اعطس ف الحمام واقول الحمد لله * * وافتكر ا...   
311  لما تعزمها ب ٧٠٠ جنيه وتقولك الحاجات البسيطة د...   

                                                 image           label  
0    data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda  
1    data/arabic_memes_fb_insta_pinterest/Pinterest...  not_propaganda  
2    data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda  
3    data/arabic_memes_fb_insta_pinterest/Pinterest...  not_propaganda  
4    data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda  
..                                                 ...             ...  
307  data/fb_memes/ArabianMemez/272646015_128128777...      propaganda  
308  data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda  
309  data/arabic_memes_fb_insta_pinterest/Pinterest...  not_propaganda  
310  data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda  
311  data/arabic_memes_fb_insta_pinterest/Pinterest...  not_propaganda  

[312 rows x 4 columns]

In [10]:
preds

id           label  \
0    data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda   
1    data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda   
2    data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda   
3    data/arabic_memes_fb_insta_pinterest/Pinterest...  not_propaganda   
4    data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda   
..                                                 ...             ...   
307  data/arabic_memes_fb_insta_pinterest/Pinterest...  not_propaganda   
308  data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda   
309  data/arabic_memes_fb_insta_pinterest/Pinterest...  not_propaganda   
310  data/arabic_memes_fb_insta_pinterest/Instagram...  not_propaganda   
311  data/arabic_memes_fb_insta_pinterest/Pinterest...  not_propaganda   

                run_id  
0    DistilBERT+ResNet  
1    DistilBERT+ResNet  
2    DistilBERT+ResNet  
3    DistilBERT+ResNet  
4    DistilBERT+ResNet  
..                 ...  
307  DistilBERT+ResNet  
308  DistilBERT+ResNet  
309  DistilBERT+ResNet  
310  DistilBERT+ResNet  
311  DistilBERT+ResNet  

[312 rows x 3 columns]

In [11]:
import pandas as pd

def analyze_misclassifications(labels_df, preds_df):
    # Merge the labels and predictions dataframes on the 'id' column
    merged_df = pd.merge(labels_df, preds_df, on='id')
    
    # Create a new column 'correct' to indicate if the prediction matches the actual label
    merged_df['correct'] = merged_df['label_x'] == merged_df['label_y']
    
    # Filter the dataframe to include only the misclassified instances
    misclassified_df = merged_df[~merged_df['correct']]
    
    # Analyze the patterns in the misclassified text
    misclassified_texts = misclassified_df['text'].tolist()
    
    # Perform text analysis on the misclassified instances
    # You can use various techniques such as:
    # - Tokenization and word frequency analysis
    # - Sentiment analysis
    # - Named entity recognition
    # - Topic modeling
    # - Linguistic patterns and features
    
    # Example: Word frequency analysis
    from collections import Counter
    
    # Tokenize the misclassified texts
    words = [word.lower() for text in misclassified_texts for word in text.split()]
    
    # Count the frequency of each word
    word_freq = Counter(words)
    
    # Print the most common words
    print("Most common words in misclassified instances:")
    print(word_freq.most_common(10))
    
    # You can perform further analysis based on your specific requirements
    
    return misclassified_df

# Call the function to analyze misclassifications
misclassified_instances = analyze_misclassifications(labels, preds)

Most common words in misclassified instances:
[('من', 13), ('على', 9), ('في', 9), ('لا', 9), ('يا', 8), ('لما', 7), ('مش', 7), ('ولا', 7), ('-', 6), ('؟', 6)]


In [13]:
import torch

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[0.1, 0.1, 0.8], [0.1, 0.1, 0.8]])

print(a * b)

tensor([[0.1000, 0.2000, 2.4000],
        [0.4000, 0.5000, 4.8000]])


In [14]:
print(1 - b)

tensor([[0.9000, 0.9000, 0.2000],
        [0.9000, 0.9000, 0.2000]])


In [27]:
import torch.nn as nn

class ConcatAttention(nn.Module):
    def __init__(self, input_dim, attention_dim):
        super(ConcatAttention, self).__init__()
        self.attention_layer = nn.Sequential(
            nn.Linear(input_dim, attention_dim),
            nn.Tanh(),
            nn.Linear(attention_dim, input_dim),
            nn.Softmax(dim=1)
        )
    
    def forward(self, text_features, image_features):
        concatenated_features = torch.cat((text_features, image_features), dim=1)
        attention_weights = self.attention_layer(concatenated_features)
        attended_features = attention_weights * concatenated_features
        print(f"Sizes: {concatenated_features.size()} | {attention_weights.size()} | {attended_features.size()} | {attended_features.sum(dim=1).size()} |")
        return attended_features.sum(dim=1)

In [28]:
m = ConcatAttention(20, 10)
a = torch.rand(10, 10)
b = torch.rand(10, 10)

print(a.size(), b.size())

torch.Size([10, 10]) torch.Size([10, 10])


In [26]:
m(a, b)

Sizes: torch.Size([10, 20]) | torch.Size([10, 20]) | torch.Size([10, 20]) | torch.Size([10]) |


tensor([0.9965, 1.1801, 1.5514, 2.0430, 1.3483, 1.6529, 1.3472, 1.8227, 2.1305,
        1.7419], grad_fn=<SumBackward1>)